### PR TITLE
94 support webcam provider plugins

### PR DESCRIPTION
**Pull request by cmuche**

### CODE REVIEW

**Comment by cmuche** [comment]
Hi @jneilliii 

I was playing around with the new webcam plugin support in OctoPrint 1.9.0 and kindly want to ask if you could take a look at some of the changes I made so I hope you don't mind I added you as a reviewer and I also hope I got the concept right.

So as I understood I can get all installed webcams (which are provided by their respecting plugins) via the `octoprint.webcams.get_webcams() ` method. Therefore (and to maintain backwards compatibility) I list the available webcams like this:
https://github.com/cmuche/octoprint-timelapseplus/blob/d3fd022e215ec255bec12517bd0418b7d68adf2c/octoprint_timelapseplus/__init__.py#L271-L274

The user can then choose the _Plugin Webcam Type_ in the settings and select a webcam from this list. For receiving a jpeg snapshot from this webcam I then use this code:

https://github.com/cmuche/octoprint-timelapseplus/blob/d3fd022e215ec255bec12517bd0418b7d68adf2c/octoprint_timelapseplus/webcamController.py#L127-L153

Is this the correct and intended way of using the new webcam architecture or did I get something wrong? 
I did test it with the _Classic Webcam_ as well as the _Test Image Plugin_ and it seems to work properly:

image
image

I'd really appreciate if you could take a look at this PR or the mentioned parts.
Thank you in advance and best regards!

**Comment by jneilliii** [comment]
I might not be the right person to review, but your logic looks sound. @crysxd who made the webcam changes might know better.

**Comment by cmuche** [comment]
@jneilliii All right, thanks four your comment and you first assessment 👍 

Hey @crysxd ! Maybe you could take a quick look here? Thad would be really great 😃

**Comment by crysxd** [comment]
The only small thing I'd change is the label "Plugin" in the UI as each plugin can provide more than one webcam. The webcam object has a display name, that should go into the list. To identify a webcam, you should save it's 'name' and not the plugin id. 

I'm trying to convert the multicam plugin at the moment, there this would be an issue 🙂

**Comment by cmuche** [comment]
Hi @crysxd and thank you for your answer! 😃 

> as each plugin can provide more than one webcam

Good point! So there can be multiple webcams that share the same provider, right?

> The webcam object has a display name, that should go into the list.

I use the display name to show in the combobox. Is this what you mean?
A pair of 'id'(?) and displayName is generated by my controller class:
https://github.com/cmuche/octoprint-timelapseplus/blob/d3fd022e215ec255bec12517bd0418b7d68adf2c/octoprint_timelapseplus/webcamController.py#L40-L46

The 'id' (to be precise: the key of the return object delivered by `octoprint.webcams.get_webcams()`) is then stored in the settings so I can identify the right webcam. What exactly do you mean by name?

**Comment by crysxd** [comment]
> So there can be multiple webcams that share the same provider, right
Yes, exactly. That's why you have to provide the webcam to the snapshot function

> The 'id' (to be precise: the key of the return object delivered b
That should be the name I think. You can also get the name from `self.WEBCAMS[k].config.name`

**Comment by cmuche** [comment]
> Yes, exactly. That's why you have to provide the webcam to the snapshot function
Okay yeah that makes sense in this context 😃 

> That should be the name I think. You can also get the name from `self.WEBCAMS[k].config.name`
All right - I'll change that in my code 👍 

Thank you very much for your review and input! I appreciate it very much!
Best regards! 😉

**Pull request merged**
